# Generated by Django 3.2.8 on 2021-11-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='address',
            new_name='speaker',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='name',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='addresses',
            name='end_time',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='start_time',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
